another change

diff --git a/hooks/pre-push b/hooks/pre-push
--- a/hooks/pre-push
+++ b/hooks/pre-push
@@ -75,9 +75,16 @@ fi
 version=`grep version pyproject.toml`
 read -r major minor patch <<<$(echo $version|sed 's/=/\n/g'|tail -1|sed 's/"//g'|tr '.' ' ')
 new_version="version = \"$major.$minor.$[patch+1]\""
-echo Incrementing patch number: old -> $version new -> $new_version
-echo updating pyproject.toml
+
+echo "Incrementing patch number: old -> $version new -> $new_version"
+echo "updating pyproject.toml"
+
 sed -i "s/$version/$new_version/g" pyproject.toml
+
+if [ $? -ne 0 ]; then
+    echo "error updating patch number!"
+    exit 1
+fi
 
 echo "All checks passed. Ready to push"
 
