back in

diff --git a/.github/workflows/on-push.yml b/.github/workflows/on-push.yml
--- a/.github/workflows/on-push.yml
+++ b/.github/workflows/on-push.yml
@@ -25,6 +25,11 @@ jobs:
         # Get version change from diff
         diff=$(git diff origin/main... pyproject.toml)
 
+        if [ -z "$diff" ]; then
+          echo "Error: Version change not found."
+          exit 1
+        fi
+
         old=$(echo "$diff" | grep -Po '(?<=-).*version.*?\K\d+\.\d+\.\d+')
         new=$(echo "$diff" | grep -Po '(?<=\+).*version.*?\K\d+\.\d+\.\d+')
 
